# Generated by Django 4.1.4 on 2023-01-28 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0002_alter_faculty_fac_id_rating_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='ratingID',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('1f4d471e-e63a-4a36-99bd-1a2c1ff946bc'), editable='false', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
