# Generated by Django 4.1.4 on 2023-01-28 15:53

import CSE.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0006_alter_faculty_fac_id_alter_post_post_snap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('3b572b44-a981-4934-b5c5-d55113c66142'), editable='false', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_snap',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', validators=[CSE.models.validate_file_extension]),
        ),
    ]
