# Generated by Django 4.1.4 on 2023-01-29 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0009_alter_faculty_fac_id_alter_post_post_snap'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='Your Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('3140131a-9b2e-4ba2-b1fe-34691290a314'), editable='false', primary_key=True, serialize=False),
        ),
    ]
