# Generated by Django 4.1.4 on 2023-01-29 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0010_faculty_name_alter_faculty_fac_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('0be3f081-80fc-49d2-b215-e6859d389b49'), editable='false', primary_key=True, serialize=False),
        ),
    ]
