# Generated by Django 4.1.4 on 2023-01-29 06:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0011_alter_faculty_fac_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('6682831b-ebc9-4fc6-88ee-ae092cc87ed7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
