# Generated by Django 4.1.4 on 2023-01-29 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0012_alter_faculty_fac_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('66398729-959c-4580-bc75-9ca1a29c3ef9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
