# Generated by Django 4.1.4 on 2023-01-29 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0013_alter_faculty_fac_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('6b5a6a49-ac52-487b-89d3-af2aa56ef223'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='Your Name', max_length=100, unique=True),
        ),
    ]
