# Generated by Django 4.1.4 on 2023-01-29 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0014_alter_faculty_fac_id_alter_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('3b133662-8db8-45dc-9eb5-d751cbf51877'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='Your Name', max_length=100),
        ),
    ]
