# Generated by Django 4.1.4 on 2023-01-29 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0015_alter_faculty_fac_id_alter_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('087cf827-4898-402e-b681-505e7c6f7639'), editable=False, primary_key=True, serialize=False),
        ),
    ]
