# Generated by Django 4.1.4 on 2023-01-29 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0016_alter_faculty_fac_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('e66ce308-efd2-42ff-b461-506f2cef3243'), editable=False, primary_key=True, serialize=False),
        ),
    ]
