# Generated by Django 4.1.4 on 2023-01-29 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0017_alter_faculty_fac_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('d244ee6a-85f0-48c0-8acf-b9a25703a443'), editable=False, primary_key=True, serialize=False),
        ),
    ]
