# Generated by Django 4.1.4 on 2023-01-29 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0018_alter_faculty_fac_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('3a5ec710-2353-42ce-ba6e-4882a95f5a76'), editable=False, primary_key=True, serialize=False),
        ),
    ]
