# Generated by Django 4.1.4 on 2023-01-29 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0019_alter_faculty_fac_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('a02a52e8-78da-4384-897a-c10855890fbf'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_Location', models.TextField(max_length=500)),
                ('event_Name', models.CharField(max_length=200)),
                ('event_Date', models.DateTimeField(auto_now_add=True)),
                ('event_details', models.TextField(max_length=1000)),
                ('fac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
