# Generated by Django 4.1.4 on 2023-01-29 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0020_alter_faculty_fac_id_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('7e4fc234-e540-49cf-97cc-87547b8ed536'), editable=False, primary_key=True, serialize=False),
        ),
    ]
