# Generated by Django 4.1.4 on 2023-01-29 18:24

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0022_alter_event_event_date_alter_faculty_fac_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='post_event',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('561f8d43-6521-4509-80ea-82b9abf03e3f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
