# Generated by Django 4.1.4 on 2023-02-01 13:22

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0023_event_post_event_alter_faculty_fac_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fac_id',
            field=models.UUIDField(default=uuid.UUID('4205ded1-1067-4939-b539-46b63e24df7b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
